version: '3.8'
services:

<%_ if (databaseType === 'postgresql') { _%>
  postgresqldb:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
<%_ } _%>
<%_ if (databaseType === 'mysql') { _%>
  mysqldb:
    image: mysql:8.0.28
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  <%_ } _%>
<%_ if (databaseType === 'mariadb') { _%>
  mariadb:
    image: mariadb:10.8.2
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
<%_ } _%>

